# Aliases of preference
alias p="sudo apt-get"
alias v="vim"
alias x="latexmk -pdf -pvc"
alias sctl="sudo systemctl"
alias g="git"
alias ga="git add"
alias gc="git commit -m"
alias gp="git push"
alias gl="git pull"
alias key="ssh-add ~/.ssh/id_rsa"
alias reinicia="sudo reboot"
alias apagate="sudo poweroff"
